### ISSUE TITLE
some ip error

### ISSUE THREAD

**Issue by mixneko** [bitwire-it/ipblocklist#2]
`223.229.222.249183.81.169.139`
`255.99.94.681.7.180.245`
`120.26.114.23145.142.132.129`
please to fix it
thank you

**Comment by Rush-er** [comment]
Thank you for reporting.

The issue is now fixed

**Comment by mraxu** [comment]
255.99.94.681.55.33.86
223.233.69.72183.81.169.238
87.236.176.24649.213.157.179
Again
