### ISSUE TITLE
Public DNS servers are also blocked

### ISSUE THREAD

**Issue by sabcabe** [bitwire-it/ipblocklist#4]
Your list includes all of the lists of https://github.com/ShadowWhisperer/IPs , which includes most of public DNS servers like cloudflare (1.1.1.1) or Google (8.8.8.8). 

Why are these added? 

This causes issues for for example guest networks that use public dns.

**Comment by Rush-er** [comment]
Thank [sabcabe](https://github.com/sabcabe) for reporting, the issue is now fixed.
Please consider supporting with a star !

Have a nice day
