### ISSUE TITLE
Smaller list from some devices

### ISSUE THREAD

**Issue by lordraiden** [bitwire-it/ipblocklist#7]
I cant' load such a big list in my firewall, can you release a smaller version maybe with 100k or 200k using some kind of prioritization? maybe not using SPAM IPs, with are a for a specific use case, forums, email etc?

Thanks anyway for the effort and for publishing it

**Comment by Rush-er** [comment]
You can do this:
1) fork my repo
2) edit the https://github.com/bitwire-it/ipblocklist/blob/main/urltable file and keep only the things you prefer
3) run the github action

Another solution is to split the content like https://github.com/mraxu did there: https://github.com/mraxu/hackip
